# Generated by Django 5.2 on 2025-05-12 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
