# Generated by Django 5.2 on 2025-05-12 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_pickup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='product',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment')], default='COD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
    ]
