# Generated by Django 5.2 on 2025-05-13 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='NewOrderItem',
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment')], default='COD', max_length=10)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('delivery_method', models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.AlterField(
            model_name='neworderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.neworder'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.neworder'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
