# Generated by Django 5.2 on 2025-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_delivery_address_order_delivery_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_instructions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_zip_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_proof',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('PICKUP', 'Pickup')], default='PICKUP', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash')], default='Cash', max_length=10),
        ),
    ]
