# Generated by Django 5.2 on 2025-05-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_payment_proof_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbatch',
            name='stock_out',
        ),
    ]
