# Generated by Django 5.2 on 2025-05-13 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_inventoryreport_prescriptionreport_salesreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreportdetail',
            name='report',
        ),
        migrations.RemoveField(
            model_name='inventoryreportdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='prescriptionreportdetail',
            name='report',
        ),
        migrations.RemoveField(
            model_name='prescriptionreportdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesreportdetail',
            name='report',
        ),
        migrations.RemoveField(
            model_name='salesreportdetail',
            name='product',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('prescriptions', 'Prescription Report')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.DeleteModel(
            name='InventoryReport',
        ),
        migrations.DeleteModel(
            name='InventoryReportDetail',
        ),
        migrations.DeleteModel(
            name='PrescriptionReport',
        ),
        migrations.DeleteModel(
            name='PrescriptionReportDetail',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
        migrations.DeleteModel(
            name='SalesReportDetail',
        ),
    ]
