# Generated by Django 5.2 on 2025-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_inventoryreportdetail_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Depleted', 'Depleted'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
    ]
