# Generated by Django 5.2 on 2025-05-14 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_productbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
