# Generated by Django 5.2 on 2025-05-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_order_pickup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='verified_by',
        ),
    ]
